# Generated by Django 2.2.2 on 2019-07-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='line_items',
            name='total_price',
        ),
        migrations.AddField(
            model_name='line_items',
            name='basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop_app.Basket'),
        ),
        migrations.AlterField(
            model_name='payment_option',
            name='card_type',
            field=models.CharField(choices=[('V', 'Visa'), ('MC', 'Mastercard'), ('AM', 'American_express'), ('PP', 'Pay_pal')], default='Visa', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
