# Generated by Django 2.2.2 on 2019-08-01 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshop_app', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book_entry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='line_items',
            name='book_entry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_entry',
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='bookshop_app.Order'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop_app.Author'),
        ),
        migrations.AddField(
            model_name='book_entry',
            name='line_items',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='bookshop_app.Line_items'),
        ),
        migrations.AddField(
            model_name='book_entry',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop_app.Review'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
